// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB97GF6IsU_YA-w_o5ta8mVICrr-CJBQxA',
    appId: '1:1072504067704:web:2f13cb4140b0f89137bf8d',
    messagingSenderId: '1072504067704',
    projectId: 'bookmet-bd',
    authDomain: 'bookmet-bd.firebaseapp.com',
    storageBucket: 'bookmet-bd.firebasestorage.app',
    measurementId: 'G-K642LRHL88',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9Gkimb56Rjihj80AkwVWylsBMAIfnJjk',
    appId: '1:1072504067704:android:5a77dc893d2dfadf37bf8d',
    messagingSenderId: '1072504067704',
    projectId: 'bookmet-bd',
    storageBucket: 'bookmet-bd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXygH5GD1OQU6GRxoOEqLFwpl69E56q9c',
    appId: '1:1072504067704:ios:9f781875ed97143537bf8d',
    messagingSenderId: '1072504067704',
    projectId: 'bookmet-bd',
    storageBucket: 'bookmet-bd.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationBookmet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXygH5GD1OQU6GRxoOEqLFwpl69E56q9c',
    appId: '1:1072504067704:ios:9f781875ed97143537bf8d',
    messagingSenderId: '1072504067704',
    projectId: 'bookmet-bd',
    storageBucket: 'bookmet-bd.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationBookmet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB97GF6IsU_YA-w_o5ta8mVICrr-CJBQxA',
    appId: '1:1072504067704:web:2d35b4d8b6fd7dfe37bf8d',
    messagingSenderId: '1072504067704',
    projectId: 'bookmet-bd',
    authDomain: 'bookmet-bd.firebaseapp.com',
    storageBucket: 'bookmet-bd.firebasestorage.app',
    measurementId: 'G-9YMQ70TZFT',
  );
}
