// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDg2AawHfaRLzhf5X9cwpTGeHSlb0Jnu5g',
    appId: '1:88533093986:web:2005df449b9d3d8e8c0b3b',
    messagingSenderId: '88533093986',
    projectId: 'bookmet-test',
    authDomain: 'bookmet-test.firebaseapp.com',
    storageBucket: 'bookmet-test.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBovjdlW4-t92CyJw0bi6IuuWYB2GACZBw',
    appId: '1:88533093986:android:c0aa71b81945a81a8c0b3b',
    messagingSenderId: '88533093986',
    projectId: 'bookmet-test',
    storageBucket: 'bookmet-test.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeVa_bOvVetRU_v6DLWR7S1m-EetF1cQM',
    appId: '1:88533093986:ios:27b8543b3533c1ce8c0b3b',
    messagingSenderId: '88533093986',
    projectId: 'bookmet-test',
    storageBucket: 'bookmet-test.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationBookmet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeVa_bOvVetRU_v6DLWR7S1m-EetF1cQM',
    appId: '1:88533093986:ios:27b8543b3533c1ce8c0b3b',
    messagingSenderId: '88533093986',
    projectId: 'bookmet-test',
    storageBucket: 'bookmet-test.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationBookmet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDg2AawHfaRLzhf5X9cwpTGeHSlb0Jnu5g',
    appId: '1:88533093986:web:a0e4c64157e9212b8c0b3b',
    messagingSenderId: '88533093986',
    projectId: 'bookmet-test',
    authDomain: 'bookmet-test.firebaseapp.com',
    storageBucket: 'bookmet-test.firebasestorage.app',
  );

}